workflows:
  maui-android-build:
    name: Build .NET MAUI Android
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
    scripts:
      - name: Install .NET SDK 9.0
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 9.0 --install-dir $DOTNET_PATH
      - name: Install .NET MAUI workloads
        script: |
          $DOTNET workload install maui maui-android --source https://aka.ms/dotnet9/nuget/index.json
      - name: Restore AndroidBridge project
        script: |
          $DOTNET restore UnityAsALib.Maui/AndroidBridge/AndroidBridge.csproj
      - name: Restore UnityUaal.Maui project
        script: |
          $DOTNET restore UnityAsALib.Maui/UnityUaal.Maui/UnityUaal.Maui.csproj
      - name: Build AndroidBridge project
        script: |
          $DOTNET build UnityAsALib.Maui/AndroidBridge/AndroidBridge.csproj -c Release -f net9.0-android --no-restore
      - name: Build UnityUaal.Maui project
        script: |
          $DOTNET build UnityAsALib.Maui/UnityUaal.Maui/UnityUaal.Maui.csproj -c Release -f net9.0-android --no-restore
    artifacts:
      - '**/*.apk'
      - '**/*.aab'

  maui-ios-simulator-build:
    name: Build .NET MAUI iOS Simulator
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
    scripts:
      - name: Install .NET SDK 7.0
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 7.0 --install-dir $DOTNET_PATH
      - name: Install .NET MAUI workloads
        script: |
          $DOTNET workload install maui maui-ios --source https://aka.ms/dotnet7/nuget/index.json
      - name: Restore UnityUaal.Maui project
        script: |
          $DOTNET restore UnityAsALib.Maui/UnityUaal.Maui/UnityUaal.Maui.csproj
      - name: Build UnityUaal.Maui for iOS Simulator
        script: |
          $DOTNET build UnityAsALib.Maui/UnityUaal.Maui/UnityUaal.Maui.csproj -c Debug -f net7.0-ios --no-restore -o ./artifacts
    artifacts:
      - ./artifacts/*.app
